# Generated by Django 3.1.6 on 2021-03-02 15:08

from django.db import migrations

#Seed role data

role_data = [
    {
        "name": "Commander",
        "organization_type": "POLICE_DEPARTMENT",
    },
    {
        "name": "Officer",
        "organization_type": "POLICE_DEPARTMENT",
    },
    {
        "name": "Commander",
        "organization_type": "EMS",
    },
    {
        "name": "Teacher",
        "organization_type": "SCHOOL",   
    },
    {
        "name": "Student",
        "organization_type": "SCHOOL",
    },
    {
        "name": "Staff",
        "organization_type": "SCHOOL",
    }
]

def seedRolesTable(apps, schema_editor):
    Role = apps.get_model('api','Role')
    for role in role_data:
        name = role["name"]
        organization_type = role["organization_type"]

        Role.objects.create(name=name, organization_type=organization_type)

def deleteAllRoles(apps, schema_editor):
    Role = apps.get_model('api','Role')
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seedRolesTable,deleteAllRoles)
    ]
